src/main/java/ca/shibatek/bean/DownloadBean.java
package ca.shibatek.bean;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

import org.springframework.util.StringUtils;

import ca.shibatek.model.MailServerAccount;
import lombok.Getter;
import lombok.Setter;

@ManagedBean
@SessionScoped
@Getter
@Setter
public class DownloadBean implements Serializable {

	private static final long serialVersionUID = 290699145124540164L;
	private MailServerAccount selectedAccount;
	private List<MailServerAccount> accounts;
	
	public DownloadBean() {
		this.accounts = new ArrayList<>();
		MailServerAccount account = new MailServerAccount();
		
		account.setUsername("test");
		account.setPassword("1111");
		account.setMailServer("GMAIL");
		
		
		MailServerAccount account2 = new MailServerAccount();
		
		account2.setUsername("test@3.com");
		account2.setPassword("1111");
		account2.setMailServer("GMAIL");
		
		accounts.add(account);
		accounts.add(account2);
	}
	
	public MailServerAccount getSelectedAccount(String email) {
		if(StringUtils.isEmpty(email)) {
			throw new IllegalArgumentException("Invalid email provided");
		}
		
		for(MailServerAccount account : accounts) {
			if(email.equals(account.getUsername())) {
				return account;
			}
		}
		
		return null;
	}
}

src/main/java/ca/shibatek/model/MailFolder.java
package ca.shibatek.model;

import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
public class MailFolder {

	private String name;
	private int messageCount;
	
}

src/main/java/ca/shibatek/model/MailServerAccount.java
package ca.shibatek.model;

import lombok.Data;

@Data
public class MailServerAccount {

	private String username;
	private String password;
	private String mailServer;
}

src/main/java/ca/shibatek/model/MailServerType.java
package ca.shibatek.model;

import lombok.Getter;

public enum MailServerType {
	GMAIL("imap.gmail.com", "993", "imaps");
	
	@Getter
	private String host;
	@Getter
	private String port;
	@Getter
	private String protocol;
	
	MailServerType(final String host, final String port, final String protocol){
		this.host = host;
		this.port = port;
		this.protocol = protocol;
	}
	
	@Override
	public String toString() {
		String value = "MailServer:";
		if(this.equals(GMAIL)) {
			value = value + "protocol= " + GMAIL.getProtocol() + "; host=" + GMAIL.getHost() + "; port=" + GMAIL.getPort();
		}
		
		return value;
	}

}

src/main/java/ca/shibatek/controller/AccountController.java
package ca.shibatek.controller;

import java.util.Collections;
import java.util.List;
import java.util.stream.Collectors;
import java.util.stream.Stream;

import org.ocpsoft.rewrite.annotation.Join;
import org.ocpsoft.rewrite.el.ELBeanName;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import ca.shibatek.model.MailServerAccount;
import ca.shibatek.model.MailServerType;

@Scope(value="session")
@Component(value="accountController")
@ELBeanName(value="accountController")
@Join(path="/accounts", to="/accounts.jsf")
public class AccountController {

	private MailServerAccount account = new MailServerAccount();
	
	public String save() {
		account = new MailServerAccount(); 
		return "/accounts.xhtml?faces-redirect=true";
	}
	
	public MailServerAccount getAccount() {
		return account;
	}
	
	public List<MailServerAccount> getAccounts() {
		return Collections.emptyList();
	}
	
	public List<String> getServerTypes() {
		return Stream.of(MailServerType.values())
					.map(MailServerType::name)
					.collect(Collectors.toList());
	}
	
}

src/main/java/ca/shibatek/controller/DownloadController.java
package ca.shibatek.controller;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

import org.ocpsoft.rewrite.annotation.Join;
import org.ocpsoft.rewrite.el.ELBeanName;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import ca.shibatek.model.MailFolder;
import ca.shibatek.model.MailServerAccount;
import lombok.Getter;
import lombok.Setter;

@Scope(value="session")
@Component(value="downloadController")
@ELBeanName(value="downloadController")
@Join(path="/download", to="/download.jsf")
public class DownloadController {

	@Getter @Setter
	private MailServerAccount account;

	/**
	 * Downloads the messages for the selected e-mail account
	 */
	public void downloadMessagesForAccount() {
		System.out.println(account);
	}
	
	/**
	 * Returns the folders for the selected e-mail account
	 */
	public List<MailFolder> getFolders(){
		
		if(account == null) {
			return Collections.emptyList();
		}
		
		List<MailFolder> listOfFolders = new ArrayList<>();
		
		MailFolder folder = new MailFolder();
		folder.setName(account.getUsername() + "folder");
		folder.setMessageCount(1);
		
		listOfFolders.add(folder);
		
		return listOfFolders;
	}
	
}

src/main/webapp/accounts.xhtml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
	  xml:lang="en"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets" 
      xmlns:p="http://primefaces.org/ui">

	<ui:composition template="layout.xhtml">
    <ui:define name="content">
    
    	<p:dataTable var="account" value="#{accountController.accounts}">
    		<p:column headerText="Username">
    			<h:outputText value="#{account.username}" />
    		</p:column>
    		<p:column headerText="Server">
    			<h:outputText value="#{account.mailServer}"/>
    		</p:column>
    	</p:dataTable>
        
        <h:form id="accountForm">
            <p:panel header="Add MailServer account">
                <h:panelGrid columns="1">
                    <p:outputLabel for="username" value="Username: " />
                    <p:inputText id="username" value="#{accountController.account.username}" />
					<p:outputLabel for="password" value="Password: " />
                    <p:password id="password" value="#{accountController.account.password}" />
                    <p:selectOneMenu value="#{accountController.account.mailServer}">
                    	<f:selectItems value = "#{accountController.serverTypes}" />
                    </p:selectOneMenu>                   
                    <h:commandButton value="Save" action="#{accountController.save}" />
                </h:panelGrid>
            </p:panel>
        </h:form>
    </ui:define>
</ui:composition>
</html>

src/main/webapp/download.xhtml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
	  xml:lang="en"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets" 
      xmlns:p="http://primefaces.org/ui">

	<ui:composition template="layout.xhtml">
    <ui:define name="content">
    
        <h:form id="downloadForm">
            <p:panel header="Select account to archive messages">
                <h:panelGrid columns="1">
                    <p:selectOneMenu value="#{downloadController.account}"
                    				 converter="accountConverter">
                    	<f:selectItems value="#{downloadBean.accounts}" 
                    				   var="account"
                    				   itemLabel="#{account.username}" 
                    				   itemValue="#{account}"/>
                    </p:selectOneMenu>                   
                    <h:commandButton value="Get Folders" action="#{downloadController.downloadMessagesForAccount}"/>
                </h:panelGrid>
            </p:panel>
        </h:form>
        
    	<p:dataTable var="folder" value="#{downloadController.folders}">
    		<p:column headerText="Name">
    			<h:outputText value="#{folder.name}" />
    		</p:column>
    		<p:column headerText="MessageCount">
    			<h:outputText value="#{folder.messageCount}"/>
    		</p:column>
    	</p:dataTable>
       
    </ui:define>
</ui:composition>
</html>

src/main/webapp/layout.xhtml
<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml"
      xml:lang="en"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

	<f:view>
    	<h:head>
	        <meta charset="utf-8" />
	        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
	        <meta name="viewport" content="width=device-width, initial-scale=1" />
	        <title>Shibatek Archiver</title>
    	</h:head>

    	<h:body>
	        <div class="ui-g">
	            <div class="ui-g-12">
	                <p:toolbar>
	                    <f:facet name="left">
	                    	<p:button href="/accounts" value="Accounts" />
	                        <p:button href="/download" value="Download" />
	                        <p:button href="/" value="Queue" />
	                        <p:button href="/" value="Completed" />
	                    </f:facet>
	                </p:toolbar>
	            </div>
	
	            <div class="ui-g-12">
	                <ui:insert name="content" />
	            </div>
	        </div>
    	</h:body>

	</f:view>

</html>